/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by: scripts/generate-routes.js
 * Generated at: 2025-10-30T03:18:14.608Z
 *
 * This file contains dynamically generated routes for documentation pages.
 * Run 'npm run generate-routes' to regenerate this file.
 */

import { Routes } from '@angular/router';

import { UseDocumentVisibilityPageComponent } from './compiled-pages/composables/browser/use-document-visibility-page.component';
import { UseMousePositionPageComponent } from './compiled-pages/composables/browser/use-mouse-position-page.component';
import { UseWindowSizePageComponent } from './compiled-pages/composables/browser/use-window-size-page.component';
import { UseParametersPageComponent } from './compiled-pages/composables/route/use-parameters-page.component';
import { UseQueryParametersPageComponent } from './compiled-pages/composables/route/use-query-parameters-page.component';
import { UseRouteDataPageComponent } from './compiled-pages/composables/route/use-route-data-page.component';
import { UseRouteFragmentPageComponent } from './compiled-pages/composables/route/use-route-fragment-page.component';
import { UseRouteParamsPageComponent } from './compiled-pages/composables/route/use-route-params-page.component';
import { UseRouteQueryParamPageComponent } from './compiled-pages/composables/route/use-route-query-param-page.component';
import { UseDebouncedSignalPageComponent } from './compiled-pages/composables/use-debounced-signal-page.component';
import { UsePreviousSignalPageComponent } from './compiled-pages/composables/use-previous-signal-page.component';
import { UseThrottledSignalPageComponent } from './compiled-pages/composables/use-throttled-signal-page.component';
import { LogChangesPageComponent } from './compiled-pages/effects/log-changes-page.component';
import { SyncLocalStoragePageComponent } from './compiled-pages/effects/sync-local-storage-page.component';
import { SyncQueryParamsPageComponent } from './compiled-pages/effects/sync-query-params-page.component';
import { CreateSharedComposablePageComponent } from './compiled-pages/utils/create-shared-composable-page.component';
import { CreateSingletonComposablePageComponent } from './compiled-pages/utils/create-singleton-composable-page.component';

export const GENERATED_DOC_ROUTES: Routes = [
  {
    path: 'composables',
    title: 'Composables',
    children: [
      {
        path: 'browser',
        title: 'Browser',
        children: [
          {
            path: 'use-document-visibility',
            component: UseDocumentVisibilityPageComponent,
            title: 'useDocumentVisibility',
          },
          {
            path: 'use-mouse-position',
            component: UseMousePositionPageComponent,
            title: 'useMousePosition',
          },
          {
            path: 'use-window-size',
            component: UseWindowSizePageComponent,
            title: 'useWindowSize',
          },
        ],
      },
      {
        path: 'route',
        title: 'Route',
        children: [
          {
            path: 'use-parameters',
            component: UseParametersPageComponent,
            title: 'useParameters',
          },
          {
            path: 'use-query-parameters',
            component: UseQueryParametersPageComponent,
            title: 'useQueryParameters',
          },
          {
            path: 'use-route-data',
            component: UseRouteDataPageComponent,
            title: 'useRouteData',
          },
          {
            path: 'use-route-fragment',
            component: UseRouteFragmentPageComponent,
            title: 'useRouteFragment',
          },
          {
            path: 'use-route-params',
            component: UseRouteParamsPageComponent,
            title: 'useRouteParams',
          },
          {
            path: 'use-route-query-param',
            component: UseRouteQueryParamPageComponent,
            title: 'useRouteQueryParam',
          },
        ],
      },
      {
        path: 'use-debounced-signal',
        component: UseDebouncedSignalPageComponent,
        title: 'useDebouncedSignal',
      },
      {
        path: 'use-previous-signal',
        component: UsePreviousSignalPageComponent,
        title: 'usePreviousSignal',
      },
      {
        path: 'use-throttled-signal',
        component: UseThrottledSignalPageComponent,
        title: 'useThrottledSignal',
      },
    ],
  },
  {
    path: 'effects',
    title: 'Effects',
    children: [
      {
        path: 'log-changes',
        component: LogChangesPageComponent,
        title: 'logChanges',
      },
      {
        path: 'sync-local-storage',
        component: SyncLocalStoragePageComponent,
        title: 'syncLocalStorage',
      },
      {
        path: 'sync-query-params',
        component: SyncQueryParamsPageComponent,
        title: 'syncQueryParams',
      },
    ],
  },
  {
    path: 'utils',
    title: 'Utils',
    children: [
      {
        path: 'create-shared-composable',
        component: CreateSharedComposablePageComponent,
        title: 'createSharedComposable',
      },
      {
        path: 'create-singleton-composable',
        component: CreateSingletonComposablePageComponent,
        title: 'createSingletonComposable',
      },
    ],
  },
];
